swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /choice_question/:
    get:
      tags:
      - choice_question
      description: get ChoiceQuestion
      operationId: ChoiceQuestionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ChoiceQuestion'
        "403":
          description: ""
    post:
      tags:
      - choice_question
      description: create ChoiceQuestion
      operationId: ChoiceQuestionController.Post
      parameters:
      - in: body
        name: body
        description: body for ChoiceQuestion content
        required: true
        schema:
          $ref: '#/definitions/models.ChoiceQuestion'
      responses:
        "201":
          description: '{int} models.ChoiceQuestion'
        "403":
          description: body is empty
  /choice_question/{id}:
    get:
      tags:
      - choice_question
      description: get ChoiceQuestion by id
      operationId: ChoiceQuestionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ChoiceQuestion'
        "403":
          description: :id is empty
    put:
      tags:
      - choice_question
      description: update the ChoiceQuestion
      operationId: ChoiceQuestionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ChoiceQuestion content
        required: true
        schema:
          $ref: '#/definitions/models.ChoiceQuestion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ChoiceQuestion'
        "403":
          description: :id is not int
    delete:
      tags:
      - choice_question
      description: delete the ChoiceQuestion
      operationId: ChoiceQuestionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.ChoiceQuestion:
    title: ChoiceQuestion
    type: object
    properties:
      Answer:
        type: string
      Chapter:
        type: string
      Course:
        type: string
      Id:
        type: integer
        format: int64
      KeyPoint:
        type: string
      OptionA:
        type: string
      OptionB:
        type: string
      OptionC:
        type: string
      OptionD:
        type: string
      OptionE:
        type: string
      Question:
        type: string
      Reason:
        type: string
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
  models.Profile:
    title: Profile
    type: object
    properties:
      Address:
        type: string
      Age:
        type: integer
        format: int64
      Email:
        type: string
      Gender:
        type: string
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: string
      Password:
        type: string
      Profile:
        $ref: '#/definitions/models.Profile'
      Username:
        type: string
tags:
- name: choice_question
  description: |
    ChoiceQuestionController operations for ChoiceQuestion
